name: Wpm
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Log in to ACR'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ARC_USERNAME }}
          password: ${{ secrets.ARC_PASSWORD }}

      - name: Get current date in yyyymmdd format
        run: echo "DATE_TIME=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: 'Build and push Management container image'
        run: |
          docker build src -f src/Microservices/Microservices/Dockerfile -t ${{ secrets.ACR_LOGIN_SERVER }}/microservices:${{ env.DATE_TIME }}.${{ github.run_number }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/microservices:${{ env.DATE_TIME }}.${{ github.run_number }}

      - name: 'Build and push Clnic container image'
        run: |
          docker build src -f src/Microservices/MicroClinic/Dockerfile -t ${{ secrets.ACR_LOGIN_SERVER }}/wpm-clinic-api:${{ env.DATE_TIME }}.${{ github.run_number }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/wpm-clinic-api:${{ env.DATE_TIME }}.${{ github.run_number }}

      - name: Deploy management to Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          acrName: ${{ secrets.ARC_USERNAME }}
          acrUsername: ${{ secrets.ARC_USERNAME }}
          acrPassword: ${{ secrets.ARC_PASSWORD }}
          containerAppName: microservices
          resourceGroup: wpm
          imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/microservices:${{ env.DATE_TIME }}.${{ github.run_number }}
          environmentVariables: Logging_LogLevel_Microsoft.EntityFrameworkCore=Debug

      - name: Deploy to Clinic Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          acrName: ${{ secrets.ARC_USERNAME }}
          acrUsername: ${{ secrets.ARC_USERNAME }}
          acrPassword: ${{ secrets.ARC_PASSWORD }}
          containerAppName: microservices
          resourceGroup: wpm
          imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/wpm-clinic-api:${{ env.DATE_TIME }}.${{ github.run_number }}
          environmentVariables: Logging_LogLevel_Microsoft.EntityFrameworkCore=Debug, Wpm__ManagementUri=http://microservices
